def _download_file(url, destFilePath, progress_function=None, ret=None):
    ret = _ret_init(ret)
    if os.path.exists(destFilePath):
        _ret_append_stdout(ret, '\nFile {0} already exists, assuming it was downloaded before'.format(destFilePath))
    else:
        try:
            force_download_file(url, destFilePath, (16 * 1024), progress_function)
        except FatalException as e:
            _ret_merge(ret, e.code, None, 'Failed to download {0} -> {1} : {2}'.format(url, destFilePath, e.reason))
        except urllib2.URLError as ue:
            _ret_merge(ret, 2, None, 'Failed to download {0} -> {1} : {2}'.format(url, destFilePath, ue.reason))
    return ret
