def _is_handled_error(self, output, is_last_time):
    if (self.resource.retry_on_locked and self.is_locked_output(output)):
        return True
    elif (self.resource.retry_on_repo_unavailability and self.is_repo_error_output(output)):
        return True
    return False
