@patch('urllib2.urlopen')
def test_fetch_url(self, urlopen_mock):
    fileCache = FileCache(self.config)
    remote_url = 'http://dummy-url/'
    test_str = ('abc' * 100000)
    test_string_io = StringIO.StringIO(test_str)
    test_buffer = MagicMock()
    test_buffer.read.side_effect = test_string_io.read
    urlopen_mock.return_value = test_buffer
    memory_buffer = fileCache.fetch_url(remote_url)
    self.assertEquals(memory_buffer.getvalue(), test_str)
    self.assertEqual(test_buffer.read.call_count, 20)
    test_buffer.read.side_effect = self.exc_side_effect
    try:
        fileCache.fetch_url(remote_url)
        self.fail('CachingException not thrown')
    except CachingException:
        pass
    except Exception as e:
        self.fail(('Unexpected exception thrown:' + str(e)))
