@patch('time.sleep')
@patch('subprocess.Popen')
def test_post_rolling_restart_datanode_not_ready(self, process_mock, time_mock):
    process = MagicMock()
    process.communicate.return_value = ['There are no DataNodes here!']
    process.returncode = 0
    process_mock.return_value = process
    try:
        self.executeScript((self.COMMON_SERVICES_PACKAGE_DIR + '/scripts/datanode.py'), classname='DataNode', command='post_rolling_restart', config_file='default.json', hdp_stack_version=self.STACK_VERSION, target=RMFTestCase.TARGET_COMMON_SERVICES)
        self.fail('Missing DataNode should have caused a failure')
    except Fail as fail:
        self.assertTrue(process_mock.called)
        self.assertEqual(process_mock.call_count, 12)
