def test_symlink_conversion_bad_linkto(self):
    '\n    Tests that a bad enum throws an exception.\n    :return:\n    '
    try:
        conf_select.convert_conf_directories_to_symlinks('hadoop', '2.3.0.0-1234', conf_select._PACKAGE_DIRS['hadoop'], link_to='INVALID')
        raise Exception('Expected failure when supplying a bad enum for link_to')
    except:
        pass
