@patch('hive_service.check_fs_root')
@patch('time.time')
@patch('socket.socket')
def test_socket_timeout(self, socket_mock, time_mock, check_fs_root_mock):
    s = socket_mock.return_value
    s.connect = MagicMock()
    s.connect.side_effect = socket.error('')
    time_mock.side_effect = [0, 1000, 2000, 3000, 4000]
    try:
        self.executeScript('2.0.6/services/HIVE/package/scripts/hive_server.py', classname='HiveServer', command='start', config_file='default.json')
        self.fail('Script failure due to socket error was expected')
    except:
        self.assert_configure_default()
        self.assertFalse(socket_mock.called)
        self.assertFalse(s.close.called)
