@patch('sys.exit')
@patch('socket.socket')
def test_checkServerReachability(self, socket_mock, exit_mock):
    setup_agent.checkServerReachability('localhost', 8080)
    self.assertTrue(socket_mock.called)
    s = socket_mock.return_value
    s.connect = MagicMock()

    def side_effect():
        raise Exception(1, 'socket is closed')
    s.connect.side_effect = side_effect
    try:
        setup_agent.checkServerReachability('localhost', 8080)
        self.fail('Should throw exception because port is closed')
    except Exception:
        self.assertTrue(exit_mock.called)
        pass
