{
  try {
    LOG.debug("Executing task #{}",taskId);
    InternalAuthenticationToken authentication=new InternalAuthenticationToken("server_action_executor");
    authentication.setAuthenticated(true);
    SecurityContextHolder.getContext().setAuthentication(authentication);
    commandReport=execute(hostRoleCommand,executionCommand);
    LOG.debug("Task #{} completed execution with status of {}",taskId,(commandReport == null) ? "UNKNOWN" : commandReport.getStatus());
  }
 catch (  Throwable t) {
    LOG.warn("Task #{} failed to complete execution due to thrown exception: {}:{}",taskId,t.getClass().getName(),t.getLocalizedMessage(),t);
    commandReport=createErrorReport(t.getLocalizedMessage());
  }
}
