def test_get_invalid_lock(self):
    '\n    Tests that an invalid lock throws an exception\n    :return:\n    '
    try:
        global_lock.get_lock('INVALID')
        self.fail('Expected an exception when trying to retrieve an invalid lock')
    except Fail:
        pass
